services:
  - type: web
    name: zobme-telegram-bot
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8196826964:AAEvCpkPFrwwoFoeNrvjOdND25s7lVJJ1Js